---
minor_changes:
  - upstream proxying - merge the ``requests`` environment for proxied requests so that environment variables such as ``REQUESTS_CA_BUNDLE`` are used appropriately (https://github.com/briantist/galactory/issues/25).
