---
minor_changes:
  - WSGI support - in addition to the bare ``create_app`` factory function, there is now a ``create_configurd_app`` factory function, which uses the same argument parsing as running from the CLI; this allows for using an external WSGI server while taking advantage of the environment variables and configuration file support to set the configuration (https://github.com/briantist/galactory/pull/28).
