---
name: Test
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.8'
          - '3.9'
          # - '3.10'  # tests totally broken.. mocks don't seem to work
          # - '3.11-dev'  # test broken:  AttributeError: module 'pathlib' has no attribute '_Accessor'
    env:
      PYTEST_ADDOPTS: '--color=yes'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Requirements
        working-directory: tests
        run: pip install -r requirements.txt

      - name: Pytest
        run: pytest tests/

  docker:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build container
        run: docker build -t galactory:latest .

      - name: Run container
        run: docker run --rm galactory --help

      - name: Login to registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to registry
        if: github.event_name == 'push'
        run: |
          UPSTREAM=ghcr.io/${{ github.repository_owner }}/galactory
          docker tag galactory ${UPSTREAM}:latest
          docker push ${UPSTREAM}:latest
